[package]
name = "oscore_nif"
version = "0.1.0"
authors = ["Thiago Esteves"]
edition = "2021"

[lib]
name = "oscore_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.38"
aes = "0.8"
ccm = "0.5"
hkdf = "0.12"
sha2 = "0.10"
ciborium = "0.2"

[dev-dependencies]
hex = "0.4"

[profile.release]
lto = true
